### ISSUE TITLE
Debug logs showing up without --debug flag

### ISSUE THREAD

**Issue by amrutprabhu** [rhasspy/wyoming-snowboy#2]
I am running this docker compose file. 

```
  snowboy:
    image: rhasspy/wyoming-snowboy
    container_name: snowboy

    entrypoint: python3
    command: >
      -m wyoming_snowboy
      --uri 'tcp://0.0.0.0:10500'
      --custom-model-dir /share/snowboy
    volumes:
      - ./snowboy-data:/data
      - ./snowboy-custom-wake-word:/share/snowboy
    ports:
      - 10500:10500
```
and when I run it, it show the debug output. 

How can I make it not print debug logs?
